app:
  name: 'XComp API Server [DEV] 🚀'
  version: '1.0.0'
  environment: 'development'
  debug: true
  port: 3000

database:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'password'
  database: 'example_db'
  sslmode: 'disable'
  max_connections: 10
  max_idle_connections: 5
  max_lifetime_minutes: 15

logging:
  # Development settings - debug level with colors
  level: 'debug'
  format: 'console'
  development: true
  force_colors: true
  # Output paths
  output_paths: 'stdout'
  error_output_paths: 'stderr'
  # Encoder configuration
  time_key: 'time'
  level_key: 'level'
  message_key: 'msg'
  caller_key: 'caller'
  stacktrace_key: 'stacktrace'
  # Time format
  time_format: 'iso8601'
  # Level format with colors
  level_format: 'capital'
  # Enable detailed debugging info
  enable_caller: true
  enable_stacktrace: true

server:
  port: 3000
  host: '0.0.0.0'
  timeout: 30s
  read_timeout: 10s
  write_timeout: 10s
  prefork: false
  cors:
    enabled: true
    allowed_origins:
      - '*'
    allowed_methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
      - 'OPTIONS'
      - 'PATCH'
    allowed_headers:
      - 'Content-Type'
      - 'Authorization'
      - 'Accept'
      - 'Origin'
      - 'X-Requested-With'

pagination:
  default_page_size: 10
  max_page_size: 100

redis:
  host: 'localhost'
  port: 6379
  password: ''
  db: 0

async:
  monitor:
    port: 8080
    enabled: true
