app:
  name: 'API Server'
  version: '1.0.0'
  environment: 'development'
  debug: true
  port: 3000

database:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'password'
  database: 'example_db'
  sslmode: 'disable'
  max_connections: 25
  max_idle_connections: 10
  max_lifetime_minutes: 30

logging:
  level: 'info'
  format: 'json'
  output: 'stdout'

server:
  port: 3000
  host: '0.0.0.0'
  timeout: 30s
  read_timeout: 10s
  write_timeout: 10s
  prefork: false
  cors:
    enabled: true
    allowed_origins:
      - '*'
    allowed_methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
      - 'OPTIONS'
    allowed_headers:
      - 'Content-Type'
      - 'Authorization'

pagination:
  default_page_size: 10
  max_page_size: 100

redis:
  host: 'localhost'
  port: 6379
  password: ''
  db: 0
