services:
  postgres:
    image: postgres:16.2-alpine
    container_name: product_api_postgres
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/migrations

  redis:
    image: redis:7.2-alpine
    container_name: product_api_redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
