services:
  postgres:
    image: postgres:16.2-alpine
    container_name: product_api_postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
