// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	Status          string             `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	ShippingCost    pgtype.Numeric     `json:"shipping_cost"`
	TaxAmount       pgtype.Numeric     `json:"tax_amount"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	Notes           pgtype.Text        `json:"notes"`
	ShippingAddress pgtype.Text        `json:"shipping_address"`
	BillingAddress  pgtype.Text        `json:"billing_address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID          pgtype.UUID    `json:"id"`
	OrderID     pgtype.UUID    `json:"order_id"`
	ProductID   pgtype.UUID    `json:"product_id"`
	ProductName string         `json:"product_name"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	TotalPrice  pgtype.Numeric `json:"total_price"`
}

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	StockQuantity int32              `json:"stock_quantity"`
	Category      pgtype.Text        `json:"category"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
