// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOrders(ctx context.Context) (int64, error)
	CountOrdersByCustomerID(ctx context.Context, customerID pgtype.UUID) (int64, error)
	// Order queries
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// Order Item queries
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DeleteOrder(ctx context.Context, id pgtype.UUID) error
	DeleteOrderItem(ctx context.Context, id pgtype.UUID) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) error
	GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]Order, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItemByID(ctx context.Context, id pgtype.UUID) (OrderItem, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	GetOrdersByCustomerID(ctx context.Context, arg GetOrdersByCustomerIDParams) ([]Order, error)
	GetOrdersByStatus(ctx context.Context, arg GetOrdersByStatusParams) ([]Order, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
}

var _ Querier = (*Queries)(nil)
