// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByCategory(ctx context.Context, category pgtype.Text) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
